"use client";

import Header from "./components/Header";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="mx-auto max-w-8xl gap-6 p-4 sm:px-6 ">
      <Header />
      {children}
    </div>
  );
}
