// import { AuthContextProvider } from "@/context/AuthContext";
import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { Inter } from "next/font/google";
import AuthProvider from "@/context/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vocslearn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-white dark:bg-black">
      <body className={`${inter.className} h-full`}>
        <AuthProvider>{children}</AuthProvider>
        <>
          {/* <AuthContextProvider user={null}> */}
          {/* <Toaster
            position="top-right"
            reverseOrder={true}
            toastOptions={{
              duration: 10000,
            }}
          /> */}
          {/* </AuthContextProvider> */}
        </>
      </body>
    </html>
  );
}
