"use client";
import { SlideBar } from "../components/settings/SlideBar";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="mx-div pt-6">
      <div className="lg:flex lg:gap-x-8 w-full overflow-x-hidden">
        <SlideBar />
        {children}
      </div>
    </main>
  );
}
